import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, sep } from 'node:path';

/**
 * Where a file's bytes live, injectable at the API boundary the way
 * `TimeSource` is (ADR-0022's shape).
 *
 * A photograph is stored here and never in the database, which is issue #11's
 * acceptance criterion; issue #12's audio and step 5's ingested documents land
 * in the same place. The vendor is an open pick — object storage is on no list
 * in the vault — so the port is what the product depends on and the adapter is
 * what deployment chooses.
 *
 * Deliberately two methods. A presigned URL is not here: it would be a second
 * thing reachable without the single edge secret ADR-0020 puts in front of
 * every route, and that ADR is still Proposed. Bytes go out through the API.
 */
export interface ObjectStore {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
}

/**
 * The local adapter: one file per key under a directory.
 *
 * What dev and every test run against, so the suite stays hermetic and needs
 * no container beyond the two it already starts. The S3-compatible adapter is
 * written when there is somewhere to deploy to; nothing above this interface
 * changes when it arrives.
 */
export class FilesystemObjectStore implements ObjectStore {
  readonly #root: string;

  constructor(root: string) {
    this.#root = root;
  }

  async put(key: string, bytes: Buffer, _contentType: string): Promise<void> {
    const path = this.#path(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.#path(key));
  }

  /**
   * Keys are generated by this product and never by a caller, so this guards
   * against a mistake here rather than against an attacker. It is cheap, and a
   * key that climbed out of the root would write over something real.
   */
  #path(key: string): string {
    const path = normalize(join(this.#root, key));
    if (!path.startsWith(this.#root + sep)) {
      throw new Error(`object key escapes the store root: ${key}`);
    }
    return path;
  }
}
