import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';

/**
 * Where a file's bytes live, injectable at the API boundary the way
 * `TimeSource` is (ADR-0022's shape).
 *
 * A photograph is stored here and never in the database, which is issue #11's
 * acceptance criterion; issue #12's audio and step 5's ingested documents land
 * in the same place. The vendor is an open pick — object storage is on no list
 * in the vault — so the port is what the product depends on and the adapter is
 * what deployment chooses.
 *
 * Deliberately no presigned URL: it would be a second thing reachable without
 * the single edge secret ADR-0020 puts in front of every route. Bytes go out
 * through the API. (ADR-0020 was Proposed when this was written and was
 * Accepted 2026-09-01; the reason stands either way, and stands harder now the
 * gate is built — issue #84.)
 *
 * `delete` arrived with the one record that may be removed, a photograph added
 * in error while its walk is open (issue #65, ADR-0066). Removing a key that is
 * not there is not an error: the caller removes the row first, so a retried or
 * half-finished removal must be able to finish.
 */
export interface ObjectStore {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/**
 * The local adapter: one file per key under a directory.
 *
 * What dev and every test run against, so the suite stays hermetic and needs
 * no container beyond the two it already starts. The S3-compatible adapter is
 * written when there is somewhere to deploy to; nothing above this interface
 * changes when it arrives.
 */
export class FilesystemObjectStore implements ObjectStore {
  readonly #root: string;

  constructor(root: string) {
    // Resolved, which normalises the path and drops any trailing separator.
    // Without it, `OBJECT_STORE_DIR=/var/data/` would have the guard below
    // compare against `/var/data//` and refuse every write to its own store.
    this.#root = resolve(root);
  }

  async put(key: string, bytes: Buffer, _contentType: string): Promise<void> {
    const path = this.#path(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.#path(key));
  }

  delete(key: string): Promise<void> {
    return rm(this.#path(key), { force: true });
  }

  /**
   * Keys are generated by this product and never by a caller, so this guards
   * against a mistake here rather than against an attacker. It is cheap, and a
   * key that climbed out of the root would write over something real.
   */
  #path(key: string): string {
    const path = normalize(join(this.#root, key));
    if (!path.startsWith(this.#root + sep)) {
      throw new Error(`object key escapes the store root: ${key}`);
    }
    return path;
  }
}
