#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The adapters read apps/api/.env, and it is gitignored at any depth.
ENV_FILE="${ENV_FILE:-apps/api/.env}"

banner "Azure for the OCR and transcription adapters"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create an Azure account"
say "You need a Microsoft account and a card. The card is for identity"
say "verification only — the free tier suspends rather than auto-charging."
say ""
open_url "https://azure.microsoft.com/free"
step "Select 'Start free' and sign in, or create a Microsoft account."
step "Complete the profile, then phone verification (SMS or call)."
step "Enter card details. Expect a temporary \$1 authorisation that reverses."
step "Accept the subscription agreement."
say ""
note "You land on a Free Trial subscription with \$200 of credit, valid 30 days."
note "At this project's volume the two services cost about \$1.50 a month, so"
note "the credit covers roughly ten years of it. There is no card-free path."
say ""
warn "Stop at the portal. Do not create any resource yet — the next stage picks it."
pause "Signed in and looking at the Azure portal?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create a resource group"
say "A resource group is just a folder. One holds everything for this project,"
say "so deleting it later removes every trace in one action."
say ""
open_url "https://portal.azure.com/#create/Microsoft.ResourceGroup"
step "Subscription: your Free Trial."
step "Resource group: rg-pmos"
step "Region: East US"
step "Review + create, then Create."
say ""
note "East US because the app runs on Fly in iad, and because Azure keys are"
note "region-scoped — a key from another region returns an authentication error."
pause "Resource group created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create ONE Microsoft Foundry resource"
say "This is the step that saves you half the work. A single Foundry resource"
say "bundles BOTH services this product needs — Document Intelligence for"
say "reading documents, and Speech for transcribing recordings — behind one"
say "endpoint and one key."
say ""
warn "Do NOT search the marketplace for 'Azure AI services'. It has been renamed"
warn "to Microsoft Foundry and the old search results lead somewhere else."
say ""
open_url "https://portal.azure.com/#create/Microsoft.CognitiveServicesAIFoundry"
step "Subscription: your Free Trial."
step "Resource group: rg-pmos"
step "Region: East US"
step "Name: pmos-ai   (or anything you like — see the warning below)"
say ""
warn "The Name becomes a permanent subdomain and can NEVER be changed. Pick it"
warn "deliberately; the only fix later is deleting and recreating the resource."
say ""
step "Leave Network, Identity, Encryption and Storage at their defaults."
step "Review + create. Tick any conditions checkbox. Create."
step "Wait for 'Your deployment is complete', then select 'Go to resource'."
say ""
note "There is no pricing-tier dropdown on this blade, and that is good news:"
note "this resource is standard-tier only, which dodges the nastiest trap in"
note "Azure AI — the free Document Intelligence tier silently returns only the"
note "FIRST TWO PAGES of any document instead of erroring, so a 40-sheet"
note "drawing set would look like it read fine."
pause "Resource created and you are on its page?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Copy the endpoint and key"
say "In the left pane, find the 'Resource Management' group and select"
say "'Keys and Endpoint'."
say ""
step "Copy KEY 1."
step "Copy the Endpoint."
say ""
warn "The endpoint MUST end in .cognitiveservices.azure.com"
warn "If you see a URL containing 'services.ai.azure.com', that is a different"
warn "endpoint on the same resource and every call will 404. Use the one on the"
warn "Keys and Endpoint blade."
say ""
note "Two keys exist so you can rotate one while the other keeps serving."
note "Either works. Neither is ever written into source."
say ""
# Asked under the names actually persisted, so a re-run offers what you
# already saved and Enter keeps it. The check below often wants a second pass.
ask AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT "Paste the Endpoint:"
ask_secret AZURE_DOCUMENT_INTELLIGENCE_KEY "Paste KEY 1 (hidden):"
AZURE_AI_ENDPOINT="$AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT"
AZURE_AI_KEY="$AZURE_DOCUMENT_INTELLIGENCE_KEY"

case "$AZURE_AI_ENDPOINT" in
  *cognitiveservices.azure.com*) ;;
  *services.ai.azure.com*)
    warn "That is the Foundry project endpoint, not the Foundry Tools one."
    warn "Go back to Keys and Endpoint and copy the cognitiveservices URL."
    ;;
  *)
    warn "That does not look like an Azure AI endpoint. Expected something like"
    warn "https://pmos-ai.cognitiveservices.azure.com/"
    ;;
esac

# One resource, so both adapters get the same pair. They stay two separate
# variable pairs because the ports are independent: either vendor can be
# pointed elsewhere later without touching the other.
write_env AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT "$AZURE_AI_ENDPOINT"
write_env AZURE_DOCUMENT_INTELLIGENCE_KEY "$AZURE_AI_KEY"
write_env AZURE_SPEECH_ENDPOINT "$AZURE_AI_ENDPOINT"
write_env AZURE_SPEECH_KEY "$AZURE_AI_KEY"
say ""
note "Written to $ENV_FILE, which is gitignored. Nothing reaches the repository."
pause "Ready to test them against the real services?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Prove the credentials actually work"
say "This sends one tiny document and a fraction of a second of silence — both"
say "generated here, nothing client-originated — and checks that every call the"
say "adapters make really lands."
say ""
note "This is the one failure the test suite cannot catch: the adapters compose"
note "an api-version into every URL, and the tests assert that URL against the"
note "same literal the adapter builds. A wrong version passes all 654 tests and"
note "then 404s every real call. Only a real request settles it."
say ""
if [[ ! -x scripts/check-vendors.sh ]]; then
  warn "scripts/check-vendors.sh not found — run this wizard from the repo root."
  exit 1
fi

if scripts/check-vendors.sh; then
  say ""
  printf '  %s✓ Both services answered.%s\n' "$GREEN" "$RESET"
else
  say ""
  warn "Something did not answer. Read the FAIL lines above."
  note "401/403 — wrong key, or a key from a different region. A brand-new key"
  note "          can also take a minute to propagate; wait and re-run."
  note "404     — wrong endpoint or wrong api-version."
  note "Do NOT turn the flags on until this passes."
fi

finish
printf '  Next: tell Claude the check passed. It will set the Fly secrets, turn\n'
printf '  on OCR=azure and TRANSCRIBER=azure, deploy, and run the on-machine\n'
printf '  verification that issue #109 and #85 are still open for.\n\n'
printf '  %sThe key is in %s and nowhere else. Do not paste it into chat.%s\n\n' "$DIM" "$ENV_FILE" "$RESET"
